version: "3.7"

services:
  mariaDB:
    container_name: mariaDB
    image: mariadb
    init: true
    volumes:
      - ./mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./mariadb/var/lib/mysql:/var/lib/mysql
      - ./mariadb/var/log/maria:/var/log/maria
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    user: root
    ports:
      - 13306:3306
    restart: always
    env_file: .env
    networks:
      - test_application_network

  application:
    build: .
    restart: always
    ports:
      - 14000:14000
    container_name: exercise_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariaDB:3306/exercise
      SPRING_DATASOURCE_USERNAME: taehoon
      SPRING_DATASOURCE_PASSWORD: taehoon123
    depends_on:
      - mariaDB
    networks:
      - test_application_network

networks:
  test_application_network:
    driver: bridge


