version: "3.7"

services:
  application:
    build: .
    restart: always
    ports:
      - 14000:8080
    container_name: exercise_app
    depends_on:
      - mariaDB
    networks:
      - test_application_network
  mariaDB:
    container_name: mariadb
    image: mariadb:10.8.3
    init: true
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    user: root
    ports:
      - 3306:3306
    restart: always
    env_file: .env
    environment:
      TZ: Asia/Seoul
networks:
  test_application_network:
    driver: bridge


