spring:
  application:
    name: "exercise"
  profiles:
    group:
      local:
        - localdb
        - swagger
      dev:
        - devdb
        - swagger
      prod:
        - proddb
    active: dev
---

server:
  port: 14000
logging:
  level:
    root: INFO
    org:
      hibernate:
        type.descriptor.sql: INFO
        SQL: DEBUG
      springframework: INFO