spring:
  config:
    activate:
      on-profile: "localdb"
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: devdb
  datasource:
    hikari:
      pool-name: excercise-core
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MariaDB103Dialect

---

spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
    url: jdbc:mariadb://mariaDB:13306/exercise
    driver-class-name: org.mariadb.jdbc.Driver
    username: taehoon
    password: taehoon123
  jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true

---

spring:
  config:
    activate:
      on-profile: "swagger"
