CREATE TABLE ABS
(
    UPPER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL ,
    TYPE_ID               INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKABS ON ABS
(ID  ASC);



ALTER TABLE ABS
    ADD CONSTRAINT  XPKABS PRIMARY KEY (ID);



CREATE TABLE ARM
(
    UPPER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL ,
    TYPE_ID               INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKARM ON ARM
(ID  ASC);



ALTER TABLE ARM
    ADD CONSTRAINT  XPKARM PRIMARY KEY (ID);



CREATE TABLE BACK
(
    UPPER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    TYPE_ID               INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL
);



CREATE UNIQUE INDEX XPKBACK ON BACK
(ID  ASC);



ALTER TABLE BACK
    ADD CONSTRAINT  XPKBACK PRIMARY KEY (ID);



CREATE TABLE CALF
(
    LOWER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    TYPE_ID               INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL
);



CREATE UNIQUE INDEX XPKCALF ON CALF
(ID  ASC);



ALTER TABLE CALF
    ADD CONSTRAINT  XPKCALF PRIMARY KEY (ID);



CREATE TABLE CARDIO
(
    ID                    INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKCARDIO ON CARDIO
(ID  ASC);



ALTER TABLE CARDIO
    ADD CONSTRAINT  XPKCARDIO PRIMARY KEY (ID);



CREATE TABLE CHEST
(
    UPPER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL ,
    TYPE_ID               INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKCHEST ON CHEST
(ID  ASC);



ALTER TABLE CHEST
    ADD CONSTRAINT  XPKCHEST PRIMARY KEY (ID);



CREATE TABLE HEAP
(
    LOWER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    TYPE_ID               INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL
);



CREATE UNIQUE INDEX XPKHEAP ON HEAP
(ID  ASC);



ALTER TABLE HEAP
    ADD CONSTRAINT  XPKHEAP PRIMARY KEY (ID);



CREATE TABLE LOWER_BODY
(
    ID                    INTEGER  NOT NULL ,
    MUSCULER_ID           INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKLOWER_BODY ON LOWER_BODY
(ID  ASC);



ALTER TABLE LOWER_BODY
    ADD CONSTRAINT  XPKLOWER_BODY PRIMARY KEY (ID);



CREATE TABLE MUSCULER_STRENGTH
(
    ID                    INTEGER  NOT NULL ,
    DATE                  DATE  NULL
);



CREATE UNIQUE INDEX XPKMUSCULER_STRENGTH ON MUSCULER_STRENGTH
(ID  ASC);



ALTER TABLE MUSCULER_STRENGTH
    ADD CONSTRAINT  XPKMUSCULER_STRENGTH PRIMARY KEY (ID);



CREATE TABLE SHOULDER
(
    ID                    CHAR(18)  NOT NULL ,
    UPPER_ID              INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL ,
    TYPE_ID               INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKSHOULDER ON SHOULDER
(ID  ASC);



ALTER TABLE SHOULDER
    ADD CONSTRAINT  XPKSHOULDER PRIMARY KEY (ID);



CREATE TABLE THIGH
(
    LOWER_ID              INTEGER  NOT NULL ,
    ID                    INTEGER  NOT NULL ,
    TYPE_ID               INTEGER  NOT NULL ,
    WEIGHT                INTEGER  NULL ,
    COUNT                 INTEGER  NULL ,
    START_TIME            DATE  NULL ,
    END_TIME              DATE  NULL
);



CREATE UNIQUE INDEX XPKTHIGH ON THIGH
(ID  ASC);



ALTER TABLE THIGH
    ADD CONSTRAINT  XPKTHIGH PRIMARY KEY (ID);



CREATE TABLE UPPER_BODY
(
    ID                    INTEGER  NOT NULL ,
    MUSCULER_ID           INTEGER  NOT NULL
);



CREATE UNIQUE INDEX XPKUPPER_BODY ON UPPER_BODY
(ID  ASC);



ALTER TABLE UPPER_BODY
    ADD CONSTRAINT  XPKUPPER_BODY PRIMARY KEY (ID);



ALTER TABLE ABS
    ADD (CONSTRAINT  R_18 FOREIGN KEY (UPPER_ID) REFERENCES UPPER_BODY(ID));



ALTER TABLE ARM
    ADD (CONSTRAINT  R_17 FOREIGN KEY (UPPER_ID) REFERENCES UPPER_BODY(ID));



ALTER TABLE BACK
    ADD (CONSTRAINT  R_14 FOREIGN KEY (UPPER_ID) REFERENCES UPPER_BODY(ID));




ALTER TABLE CALF
    ADD (CONSTRAINT  R_23 FOREIGN KEY (LOWER_ID) REFERENCES LOWER_BODY(ID));




ALTER TABLE CHEST
    ADD (CONSTRAINT  R_15 FOREIGN KEY (UPPER_ID) REFERENCES UPPER_BODY(ID));



ALTER TABLE HEAP
    ADD (CONSTRAINT  R_21 FOREIGN KEY (LOWER_ID) REFERENCES LOWER_BODY(ID));


ALTER TABLE LOWER_BODY
    ADD (CONSTRAINT  R_20 FOREIGN KEY (MUSCULER_ID) REFERENCES MUSCULER_STRENGTH(ID));



ALTER TABLE SHOULDER
    ADD (CONSTRAINT  R_8 FOREIGN KEY (UPPER_ID) REFERENCES UPPER_BODY(ID));



ALTER TABLE THIGH
    ADD (CONSTRAINT  R_22 FOREIGN KEY (LOWER_ID) REFERENCES LOWER_BODY(ID));



ALTER TABLE UPPER_BODY
    ADD (CONSTRAINT  R_6 FOREIGN KEY (MUSCULER_ID) REFERENCES MUSCULER_STRENGTH(ID));